"""
第39章：3D视觉与神经辐射场 - 代码演示入口
"""

print("3D视觉与神经辐射场 - 代码实现")
print("=" * 50)
print("\n文件说明：")
print("1. nerf_from_scratch.py - NeRF核心实现")
print("   - 位置编码")
print("   - NeRF网络（MLP）")
print("   - 射线生成")
print("   - 体积渲染")
print("\n2. train_nerf.py - 训练脚本")
print("   - 数据集加载")
print("   - 训练循环")
print("   - 模型保存")
print("\n3. demo_3dgs.py - 3DGS概念演示")
print("   - 3D高斯表示")
print("   - 高斯溅射")
print("   - 球谐函数可视化")
print("\n使用方法：")
print("  python nerf_from_scratch.py  # 测试NeRF实现")
print("  python train_nerf.py         # 训练NeRF")
print("  python train_nerf.py render  # 渲染测试")
print("  python demo_3dgs.py          # 3DGS演示")
print("  python demo_3dgs.py sh       # 球谐函数可视化")
